#Site configuration
title: Met Resultaat
name:  Met Resultaat
author: Mette Reitsma
work:  Improvement manager
year: 2019
profile: mette-reitsma.jpg
design: raybogman.com

# Navigation
nav1: "Over"
nav2: "Kernwaarden"
nav3: "Projecten"
nav4: "Wie is Mette?"

# Section1
sec1: "Met Resultaat"
sec2: "De kracht van verbeter management nu binnen hand bereik"
sec3: "Met Resultaat helpt met het managen en realiseren van verbeteringen en veranderingen. Dit op basis van LEAN principes maar vooral ook veel gezond verstand en pragmatiek zodat het simpel blijft."

# Section 2
sec4: "Kernwaarden"
sec5: "Neem contact op als:"
icon1: "fas fa-code"
icont1: "Jouw organisatie de klanttevredenheid wil verbeteren"
icon2: "fa-cubes"
icont2: "Jouw organisatie efficiënter wil gaan werken"
icon3: "fa-book"
icont3: "Jouw organisatie de levertijd wil verkorten"
icon4: "fa-coffee"
icont4: "Jouw organisatie LEAN principes wil implementeren"

# Section 3
sec6: "Projecten"
sec7: "Overzicht reeds voltooide projecten en klantervaringen."
sec8: "Canon"
sec9: "Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer adipiscing ornare amet."
#sec10: "Terraformed a small moon"
#sec11: "Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer adipiscing ornare amet."
#sec12: "Snapped dark matter in the wild"
#sec13: "Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer adipiscing ornare amet."

# Section 4
sec14: "Wie is Mette?"
sec15: "Oprichter en eigenaar achter Met Resultaat is Mette Reitsma. Ze is enthousiast, slim, gedreven en zeer resultaatgericht. Met veel energie en overtuigingskracht brengt zij een organisatie in beweging. Ze leert snel en stelt veel vragen om tot de kern te komen. Betrouwbaarheid is voor haar cruciaal."
sec16: "Mette heeft ruim 20 jaar ervaring en heeft daarbij meerdere organisaties in beweging gebracht. Ze maakt problemen graag kleiner zodat ze in kleine stappen op te lossen zijn. Ze zorgt continu dat kwaliteit, tijd en investering met elkaar in balans zijn."

# Social Links
#facebook: username
#twitter:  username
#google: username
#instagram: username
#pinterest: username
linkedin: mettereitsma
#youtube: username
#spotify: username
#lastfm: username
#github: username
#stackoverflow: username
#quora: username
#reddit: username
#medium: username
#vimeo: username
#keybase: username
email: mette@resulta.at
